---

name: Tracker Validator
description: Bugzilla and Jira validation for Pull Requests

branding:
  icon: bookmark
  color: blue

inputs:
  pr-metadata:
    required: true
    description: Pull Request metadata

  tracker:
    description: tracker ID
  tracker-type:
    description: tracker type, supported values are 'bugzilla' and 'jira'

  product:
    description: Product name
  component:
    required: true
    description: Component name

  bugzilla-instance:
    description: Bugzilla instance URL
    default: https://bugzilla.redhat.com
  bugzilla-api-token:
    description: Bugzilla API TOKEN

  jira-instance:
    description: Jira instance URL
    default: https://issues.redhat.com
  jira-api-token:
    description: Jira API TOKEN

  token:
    required: true
    description: GitHub TOKEN or PAT

runs:
  using: node16
  main: dist/index.js
