---
name: Linting suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5

      - name: Use Node.js 18.x
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint
