---
name: Linting suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9

      - name: Use Node.js 18.x
        uses: actions/setup-node@ca2d4e0cdd8c63d9ebfedc3d16d450a870caf31c
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prettier
        run: yarn run format-check

      - name: ESLint
        run: yarn run lint
