---

name: GitHub Tag Update

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9

      - name: Update tag
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
          token: ${{ secrets.GITHUB_TOKEN }}

...
